[package]
name = "streamline"
version = "0.1.0"
edition = "2021"

[lib]
name = "streamline"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy-primitives = "0.5.4"
alloy-sol-types = "0.5.4"
prost-wkt-types = "0.4.2"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
substreams = "0.5.12"
substreams-alloy-helpers = {git = "https://github.com/MercuricChloride/substreams-alloy-helpers"}
substreams-database-change = "1.3.0"
substreams-ethereum = "0.9.9"
